name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

env:
  GO_VERSION: 1.18

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Test
        run: go test -covermode atomic -coverprofile coverage.out ./...
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: coverage.out
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: latest
          args: --fast
          # skip cache because of flaky behaviors
          skip-build-cache: true
          skip-pkg-cache: true
